import { describe, expect, it } from 'vitest';
import { computeCapex, computeDepreciation } from '../capex';
import { DEFAULT_LEAGUE_CONFIG } from '../config';

/** Literal native MECOM v2.07 HERMES1 report/save case, period 4, firm 1.
 * Read-only original run: opening book $26062 (651 machines + $22 remainder).
 * Report fixture SHA-256: b4ae68f8e6f123be6c8b698031001035042dd887f0b12acffec12ba637857c65.
 * Expected amounts are original observations, not values generated by this engine.
 */
describe('Original MECOM capital depreciation', () => {
  it('depreciates the complete opening book value, including its remainder', () => {
    expect(computeCapex({ machines: 651, amortFundRemainder: 22, capexGross: 3000 },
      DEFAULT_LEAGUE_CONFIG)).toEqual({
      depreciation: 1303,
      netInvestment: 1697,
      newMachines: 42,
      capexAdditions: 1680,
      amortFundRemainder: 39,
      capacityNext: 693,
      capexBookValue: 27759,
    });
  });

  it('keeps two-argument callers compatible and rounds half dollars upward', () => {
    expect(computeDepreciation(525, DEFAULT_LEAGUE_CONFIG)).toBe(1050);
    expect(computeDepreciation(651, DEFAULT_LEAGUE_CONFIG, 9)).toBe(1302);
    expect(computeDepreciation(651, DEFAULT_LEAGUE_CONFIG, 10)).toBe(1303);
    expect(computeDepreciation(651, DEFAULT_LEAGUE_CONFIG, 30)).toBe(1304);
    expect(computeDepreciation(1, {
      ...DEFAULT_LEAGUE_CONFIG, machineCost: 30, machineLifespanPeriods: 4,
    })).toBe(8);
  });

  // Literal HERMES1 periods 1..4, all eight firms, from the read-only original
  // report fixture; book totals separately confirmed in native original saves.
  it('replays original capacities and book totals without cumulative drift', () => {
    const periods = [
      { gross: [3000, 5050, 5000, 2010, 3000, 1050, 4000, 24050],
        capacity: [573, 625, 623, 549, 573, 525, 598, 1100], book: 206760 },
      { gross: [3000, 1250, 5000, 2100, 1000, 2250, 7000, 9760],
        capacity: [620, 625, 717, 574, 570, 555, 743, 1289], book: 227780 },
      { gross: [2500, 1250, 13000, 1600, 500, 2310, 120, 15000],
        capacity: [651, 625, 1006, 585, 554, 585, 709, 1599], book: 252671 },
      { gross: [3000, 1250, 10000, 1800, 60, 1170, 500, 25000],
        capacity: [693, 625, 1206, 601, 527, 585, 686, 2144], book: 282818 },
    ];
    let opening = Array.from({ length: 8 }, () => ({ machines: 525, amortFundRemainder: 0 }));
    expect(opening.reduce((sum, firm) => sum + firm.machines * 40, 0)).toBe(168000);
    for (const period of periods) {
      const closing = opening.map((firm, i) => computeCapex({
        ...firm, capexGross: period.gross[i],
      }, DEFAULT_LEAGUE_CONFIG));
      expect(closing.map(firm => firm.capacityNext)).toEqual(period.capacity);
      expect(closing.reduce((sum, firm) => sum + firm.capexBookValue, 0)).toBe(period.book);
      opening = closing.map(firm => ({
        machines: firm.capacityNext, amortFundRemainder: firm.amortFundRemainder,
      }));
    }
  });
});
